### ISSUE TITLE
bad formatting of plugin description

### ISSUE THREAD

**Issue by Bananeweizen** [jenkinsci/next-executions-plugin#114]
### Jenkins and plugins versions report

n/a

### What Operating System are you using (both controller, and any agents involved in the problem)?

n/a

### Reproduction steps

1. open plugin manager
2. filter for "next"

### Expected Results

plugin description without formatting errors

### Actual Results

The plugin description contains markdown style formatting, but that is not supported by Jenkins:
![grafik](https://github.com/jenkinsci/next-executions-plugin/assets/406876/dbeef5d6-a654-4b02-a1b4-067de568eaa2)

**Comment by IbraheemHaseeb7** [comment]
I would like to fix this issue

**Comment by jonesbusy** [comment]
Fixed on https://github.com/jenkinsci/next-executions-plugin/pull/116
