### ISSUE TITLE
If the job name is long, the time information is not visible.

### ISSUE THREAD

**Issue by jihunparkme** [jenkinsci/next-executions-plugin#123]
### What feature do you want to see added?

I found a problem where time information is not visible when the job name is long.
I think job name is important, but time information is also important.

<img width="352" alt="asis" src="https://github.com/jenkinsci/next-executions-plugin/assets/35000355/d35432c1-21f5-4356-88bb-2f9228e02a92">

.

So, if the job name exceeds a certain length, I suggest replacing the later characters with "...."
Please refer to the example below

<img width="347" alt="tobe" src="https://github.com/jenkinsci/next-executions-plugin/assets/35000355/55e7a306-e3b3-4839-b0e6-1e2c97eb5dce">

.

Thank you for providing a good plug-in.
Please consider my suggestion. Thank you.

### Upstream changes

```javascript
cutJobName(name, limit) {
    if (name.length > limit) {
        return name.substring(0, limit) + '...';
    }
    return name;
}
```

**Comment by jonesbusy** [comment]
Definitely need to be fixed, but I'm wonder if there is better CSS solution than just trimming the job name ?

**Comment by jihunparkme** [comment]
I think adding line breaks could also be a solution.

So, I found a CSS property called word-break.
The word-break property specifies how words should break when reaching the end of a line.
(ref. https://www.w3schools.com/cssref/css3_pr_word-break.php)

AS-IS

<img width="343" alt="스크린샷 2024-06-13 오전 10 51 32" src="https://github.com/jenkinsci/next-executions-plugin/assets/35000355/5764db15-6c92-4880-92db-0db00bac9ae3">

```html
<tr>
    <td class="pane"><a tooltip="SampleJobNaaaaaaaaaaaaaaaaaaaaaaaaaaaame" href="xxx"
            title="SampleJobNaaaaaaaaaaaaaaaaaaaaaaaaaaaame">
            SampleJobNaaaaaaaaaaaaaaaaaaaaaaaaaaaame</a></td>
    <td tooltip="(in )" class="pane" title="(in )">2024/06/13 10:49</td>
</tr>
```
...

TO-BE
<img width="337" alt="스크린샷 2024-06-13 오전 10 54 04" src="https://github.com/jenkinsci/next-executions-plugin/assets/35000355/2695c16e-11f0-424d-a198-9f4bafdf7209">

```html
<tr>
    <td class="pane"><a tooltip="SampleJobNaaaaaaaaaaaaaaaaaaaaaaaaaaaame" href="xxx"
            title="SampleJobNaaaaaaaaaaaaaaaaaaaaaaaaaaaame" style="word-break: break-all;">
            SampleJobNaaaaaaaaaaaaaaaaaaaaaaaaaaaame</a></td>
    <td tooltip="(in )" class="pane" title="(in )">2024/06/13 10:49</td>
</tr>
```

Simply add the word-break: break-all; option to an a tag that has the job name.

Thank you.

**Comment by jihunparkme** [comment]
While reviewing the project for creating a pull request, I discovered that the issue I requested has already been addressed in version 327.v136ff959e97b_
https://github.com/jenkinsci/next-executions-plugin/pull/109

It seems appropriate to close this issue.
Thank you.
