### ISSUE TITLE
The same style as the standard ones in "Build Queue" and "Build Executor Status"

### ISSUE THREAD

**Issue by gil9red** [jenkinsci/next-executions-plugin#59]
Hello!

Append "pane" class to td elements in widgets (such as Next Executions) the same style as the standard ones in "Build Queue" and "Build Executor Status".

For convenience, I made a script for Tampermonkey that adds the class: https://gist.github.com/gil9red/d29ef875d76e45b9a2df5408dacd3b14

You can check the same code in your browser:
```javascript
document.querySelectorAll("#next-exec table td").forEach((item) => {
    item.classList.add("pane");
});
```

Result:
![Images](https://github.com/jenkinsci/next-executions-plugin/assets/6244078/efd89c9f-4737-42ee-9bbb-91dd6ce9cb23)

**Comment by jonesbusy** [comment]
Hi, which version of Jenkins Core and plugin are you using ?

**Comment by gil9red** [comment]
Actual on current time:
 * Jenkins: 2.430
 * next-executions: 229.v0a_47a_09840df

**Comment by jonesbusy** [comment]
Thanks. I've open a PR https://github.com/jenkinsci/next-executions-plugin/pull/60 to add the missing class
