### ISSUE TITLE
Add an option to remove disabled jobs from next execution

### ISSUE THREAD

**Issue by gandadil** [jenkinsci/next-executions-plugin#61]
### What feature do you want to see added?

I want a global option to remove disabled jobs to show on next executions in jenkins main page.

Thanks

**Comment by jonesbusy** [comment]
Sounds more like a bug that a missing feature.

Disabled jobs are never executed by cron so I should they should not appear on the list of widget

**Comment by jonesbusy** [comment]
I confirm it works for AbstractProject (Like freestyle jobs) but not Workflow jobs

**Comment by jonesbusy** [comment]
Tentative fix on https://github.com/jenkinsci/next-executions-plugin/pull/62

**Comment by gandadil** [comment]
> Sounds more like a bug that a missing feature.
> 
> Disabled jobs are never executed by cron so I should they should not appear on the list of widget

Well, so this is a bug
<img width="173" alt="image" src="https://github.com/jenkinsci/next-executions-plugin/assets/48427120/03f98a77-a293-4892-bc58-0287b3976360">

These two jobs are disabled on my jenkins server

**Comment by jonesbusy** [comment]
Can you test that 239.v27031b_e26418 fixes your issue ?

**Comment by gandadil** [comment]
Tested. It's perfect now. Thank you
