### ISSUE TITLE
Unhandled NullPointer Exception

### ISSUE THREAD

**Issue by debayangg** [jenkinsci/next-executions-plugin#77]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

OS: Kali GNU/Linux Rolling x86_64
Jenkins : Compiled from source
Agents/Controllers : None

### Reproduction steps

1. In NextBuilds.java, formatDate(), calls this.getDescriptor().getDateFormat(), but getDescriptor() can return a null value which goes unhandled.

### Expected Results

NullPointer Exception handled when getDescriptor() returns a null value.

### Actual Results

NullPointer Exception thrown when getDescriptor() throws a null value.

### Are you interested in contributing a fix?

I would like to work on this issue.

**Comment by jonesbusy** [comment]
In which cases `this.getDescriptor()` can return null ? Can you elaborate ?

Before fixing a supposed bug I would like to have a test that show that the issue exists

**Comment by debayangg** [comment]
I was working on writing a test when I noticed this behavior

**Comment by debayangg** [comment]
Should I incorporate the above code into a test?

**Comment by jonesbusy** [comment]
I think would be better to write tests using JenkinsRule instead of mocking jobs. I'm not surprised you can NullPointer during unit test phase doing so

**Comment by debayangg** [comment]
Okay I will try to write my tests using JenkinsRule then, thanks for the advice, I was really confused on how to create a valid instance for the tests.

**Comment by jonesbusy** [comment]
Closing the issue then. Feel free to reopen if you reproduce it with non-mocked jobs
