### ISSUE TITLE
Widget Display mode broken

### ISSUE THREAD

**Issue by TobiX** [jenkinsci/next-executions-plugin#78]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

(Info from `mvn hpi:run`)
  ```text
Jenkins: 2.426.2
OS: Linux - 6.6.9-amd64
Java: 11.0.22-ea - Debian (OpenJDK 64-Bit Server VM)
---
bouncycastle-api:2.28
caffeine-api:3.1.8-133.v17b_1ff2e0599
instance-identity:173.va_37c494ec4e5
ionicons-api:56.v1b_1c8c49374e
javax-activation-api:1.2.0-6
javax-mail-api:1.6.2-9
next-executions:999999-SNAPSHOT (private-3ab43223-tobias)
parameterized-scheduler:255.v73827fcdf618
scm-api:683.vb_16722fb_b_80b_
script-security:1294.v99333c047434
structs:325.vcb_307d2a_2782
workflow-api:1283.v99c10937efcb_
workflow-job:1385.vb_58b_86ea_fff1
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:865.v43e78cc44e0d
```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux on server/client

### Reproduction steps

1. Create a scheduled job with a very long name
2. Try to toggle "Widget Display mode" to different modes (Truncate, Fixed Width, Jenkins)

### Expected Results

Different display of the sidebar.

### Actual Results

All variants of the sidebar look and work the same.

### Anything else?

When using the modes "Truncate" or "Fixed Width", the CSS rule [`table-layout: fixed;`](https://github.com/jenkinsci/next-executions-plugin/blob/main/src/main/resources/hudson/plugins/nextexecutions/NextExecutionsWidget/index.jelly#L7) leads to a totally broken layout (sidebar is too wideeeeeeeeeeee) whenever the browser window is between 900px and 1170px... (Seems to be some middle ground between the mobile & desktop layouts)

### Are you interested in contributing a fix?

My (stupid) fix would just remove the "Widget Display mode" and remove the associated styles, so it looks as if "Jenkins" is selected.

**Comment by jonesbusy** [comment]
>> My (stupid) fix would just remove the "Widget Display mode" and remove the associated styles, so it looks as if "Jenkins" is selected.

I'm fine for it. I never used this feature. I guess was implemented long time ago when widget where very different than now (like table etc...).
