### ISSUE TITLE
Update widget with message when no execution are founds

### ISSUE THREAD

**Issue by jonesbusy** [jenkinsci/next-executions-plugin#83]
### What feature do you want to see added?

Update widget with message when not execution are founds

To be consistent with other widget (like build queue) that display `No builds in the queue.`

![Screenshot from 2024-01-13 13-47-26](https://github.com/jenkinsci/next-executions-plugin/assets/825750/8a9bf4ed-55a8-4ad2-831c-2bb27838bf7f)

**Comment by l3002** [comment]
Hi @jonesbusy, Sorry but I'm not able to understand what kind of message update are you looking for in the widgets and what should trigger this update. Could you please clarify this a bit more?

**Comment by jonesbusy** [comment]
See screenshot there is no message now.

Something similar of the build queue widget as you can see.

It's confusing now to see an empty widget that is not indicating that there is no execution

**Comment by l3002** [comment]
Okay, So, Correct me if I am wrong, you require a new widget which displays the jobs which are not in execution right now or a message which displays that that no job execution is taking place right now.

**Comment by jonesbusy** [comment]
Like the build queue. Just a message like "No next executions found."

If you look carefully at the screen, the UI is not consistent. All widgets are empty, but only the next execution one doesn't display a proper message.

**Comment by l3002** [comment]
Okay... I get it now. Sorry, I wasn't able to spot it at first. Fine, I believe I can try to fix this. Could you please assign this issue to me?

**Comment by jonesbusy** [comment]
We don't assign issues so that everyone can pick it up.

Just submit a PR and I will review it.

**Comment by l3002** [comment]
Oh. Okay. I'll try to submit a PR by next week. I need some time to understand the codebase first and Again thanks for the clarification.

**Comment by jonesbusy** [comment]
Needed to revert because of regression

**Comment by jonesbusy** [comment]
Implemented
